# Generated by Django 5.0.7 on 2025-04-05 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('qqz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='topic',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='studymaterial',
            unique_together={('user', 'level', 'topic')},
        ),
    ]
