# Generated by Django 5.2.10 on 2026-08-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classroom",
            "0002_submission_file_classexam_classschedule_classsession_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="live_url",
            field=models.URLField(
                blank=True,
                help_text="لینک جلسه آنلاین (اسکای\u200cروم، گوگل\u200cمیت…). خالی = اتاق خودکار Jitsi",
            ),
        ),
    ]
