# Generated by Django 5.2.10 on 2026-08-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_dailyactivity"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="کلید API (مثلاً MetisAI). خالی بماند تا از .env خوانده شود.",
                        max_length=255,
                    ),
                ),
                (
                    "base_url",
                    models.CharField(
                        blank=True,
                        help_text="آدرس پایه API سازگار با OpenAI. خالی = مقدار .env",
                        max_length=255,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        help_text="نام مدل (مثلاً gpt-4o-mini). خالی = مقدار .env",
                        max_length=100,
                    ),
                ),
                (
                    "daily_limit",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="سقف درخواست AI هر کاربر در روز. صفر = مقدار .env",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="اگر خاموش شود، همه\u200cی قابلیت\u200cهای AI موقتاً غیرفعال می\u200cشوند.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Configuration",
                "verbose_name_plural": "AI Configuration",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student / زبان\u200cآموز"),
                    ("teacher", "Teacher / معلم"),
                ],
                default="student",
                max_length=10,
            ),
        ),
    ]
