# Generated by Django 5.2.10 on 2026-08-29 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def dedupe_user_levels(apps, schema_editor):
    """قبل از یکتاسازی، اگر کاربری چند ردیف سطح دارد فقط جدیدترین را نگه دار."""
    UserLevel = apps.get_model('app', 'UserLevel')
    seen = set()
    for level in UserLevel.objects.order_by('user_id', '-created_at'):
        if level.user_id in seen:
            level.delete()
        else:
            seen.add(level.user_id)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_aiconfig_userprofile_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedupe_user_levels, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="userlevel",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
