# Generated by Django 5.2.10 on 2026-08-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_userlevel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="xp",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
